"use client";
import {FormEvent,useEffect,useState} from "react";
type Site={id:string;name:string;address?:string|null;latitude?:number|null;longitude?:number|null};
type Contact={id:string;phone:string;name?:string|null};
type C={id:string;name:string;active:boolean;sites:Site[];contacts:Contact[]};

export default function CustomerManager(){
 const [rows,setRows]=useState<C[]>([]),[name,setName]=useState("");
 const [customerId,setCustomerId]=useState(""),[siteName,setSiteName]=useState(""),[cep,setCep]=useState(""),[address,setAddress]=useState(""),[latitude,setLatitude]=useState(""),[longitude,setLongitude]=useState("");
 const [contactCustomer,setContactCustomer]=useState(""),[siteId,setSiteId]=useState(""),[phone,setPhone]=useState(""),[contactName,setContactName]=useState("");
 const load=async()=>{const r=await fetch("/api/customers");const d=await r.json();setRows(d);if(d[0]){setCustomerId(x=>x||d[0].id);setContactCustomer(x=>x||d[0].id)}};
 useEffect(()=>{void load()},[]);
 async function send(url:string,body:unknown){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){const x=await r.json().catch(()=>({}));alert(x.error||"Não foi possível salvar");return false}await load();return true}
 async function addCustomer(e:FormEvent){e.preventDefault();if(await send("/api/customers",{name})){setName("")}}
 async function geocodeAddress(a:string){if(!a.trim())return;try{const r=await fetch("/api/geocode?address="+encodeURIComponent(a.trim())),j=await r.json();if(!r.ok)return;setLatitude(String(j.latitude));setLongitude(String(j.longitude))}catch{}}async function lookupCep(){const p=cep.replace(/\D/g,"");if(p.length!==8)return alert("Informe um CEP com 8 dígitos.");try{const r=await fetch("https://viacep.com.br/ws/"+p+"/json/"),j=await r.json();if(!r.ok||j.erro)return alert("CEP não encontrado.");const a=[j.logradouro,j.bairro,j.localidade,j.uf].filter(Boolean).join(", ");setAddress(a);await geocodeAddress(a)}catch{alert("Não foi possível consultar o CEP.")}}async function addSite(e:FormEvent){e.preventDefault();if(await send("/api/sites",{customerId,name:siteName,address,latitude,longitude})){setSiteName("");setCep("");setAddress("");setLatitude("");setLongitude("")}}
 async function addContact(e:FormEvent){e.preventDefault();if(await send("/api/contacts",{customerId:contactCustomer,siteId:siteId||null,phone,name:contactName,authorized:true})){setPhone("");setContactName("")}}
 async function mutate(url:string,method:string,body:any){const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok){alert(j.error||"Operação não realizada");return false}await load();return true}async function editCustomer(x:C){const name=prompt("Nome / razão social",x.name);if(name&&name.trim()!==x.name)await mutate("/api/customers","PATCH",{id:x.id,name})}async function deleteCustomer(x:C){if(confirm("Excluir o cliente "+x.name+"? Esta ação só será permitida se não houver atendimentos vinculados."))await mutate("/api/customers","DELETE",{id:x.id})}async function editSite(x:Site){const name=prompt("Nome do estabelecimento",x.name);if(!name)return;const address=prompt("Endereço",x.address||"")??x.address??"";const latitude=prompt("Latitude",x.latitude?.toString()||"")??"";const longitude=prompt("Longitude",x.longitude?.toString()||"")??"";await mutate("/api/sites","PATCH",{id:x.id,name,address,latitude,longitude})}async function deleteSite(x:Site){if(confirm("Excluir o local "+x.name+"?"))await mutate("/api/sites","DELETE",{id:x.id})}async function editContact(x:Contact){const name=prompt("Nome do contato",x.name||"")??x.name??"";const phone=prompt("WhatsApp (55 + DDD + número)",x.phone);if(phone)await mutate("/api/contacts","PATCH",{id:x.id,name,phone,authorized:true})}async function deleteContact(x:Contact){if(confirm("Excluir este WhatsApp autorizado?"))await mutate("/api/contacts","DELETE",{id:x.id})}async function toggleCustomer(id:string,active:boolean){await fetch("/api/customers",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,active})});await load()} const sites=rows.find(x=>x.id===contactCustomer)?.sites||[];
 return <div className="admin-grid">
  <section><h3>Novo cliente</h3><form onSubmit={addCustomer} className="form"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nome / razão social"/><button>Cadastrar cliente</button></form></section>
  <section><h3>Estabelecimento / local</h3><form onSubmit={addSite} className="form"><select required value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Selecione o cliente</option>{rows.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input required value={siteName} onChange={e=>setSiteName(e.target.value)} placeholder="Nome do estabelecimento"/><div className="cep-row"><input inputMode="numeric" maxLength={9} value={cep} onChange={e=>setCep(e.target.value)} onBlur={()=>cep.replace(/\D/g,"").length===8&&lookupCep()} placeholder="CEP"/><button type="button" className="cep-button" onClick={lookupCep}>BUSCAR CEP</button></div><input value={address} onChange={e=>setAddress(e.target.value)} onBlur={()=>geocodeAddress(address)} placeholder="Endereço"/><div className="dispatch"><input inputMode="decimal" value={latitude} onChange={e=>setLatitude(e.target.value)} placeholder="Latitude (ex.: -7.2300)"/><input inputMode="decimal" value={longitude} onChange={e=>setLongitude(e.target.value)} placeholder="Longitude (ex.: -39.3100)"/></div><small>Informe latitude e longitude para habilitar a confirmação de chegada em perímetro de 100 m.</small><button>Cadastrar local</button></form></section>
  <section><h3>WhatsApp autorizado</h3><form onSubmit={addContact} className="form"><select required value={contactCustomer} onChange={e=>{setContactCustomer(e.target.value);setSiteId("")}}><option value="">Selecione o cliente</option>{rows.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={siteId} onChange={e=>setSiteId(e.target.value)}><option value="">Todos os locais do cliente</option>{sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input value={contactName} onChange={e=>setContactName(e.target.value)} placeholder="Nome do contato"/><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="WhatsApp: 55 + DDD + número"/><button>Autorizar WhatsApp</button></form></section>
  <section className="wide"><h3>Base cadastrada</h3><div className="list">{rows.map(c=><article key={c.id}><div className="row-between"><b>{c.name}</b><div className="record-actions"><button className="mini" onClick={()=>editCustomer(c)}>EDITAR</button><button className="mini" onClick={()=>toggleCustomer(c.id,!c.active)}>{c.active?"INATIVAR":"REATIVAR"}</button><button className="mini danger" onClick={()=>deleteCustomer(c)}>EXCLUIR</button></div></div><small>{c.active?"ATIVO":"INATIVO"} • {c.sites.length} local(is) • {c.contacts.length} WhatsApp(s)</small>{c.sites.map(x=><div className="base-item" key={x.id}><small>• {x.name}{x.address?" — "+x.address:""}{x.latitude!=null&&x.longitude!=null?" • GPS configurado":""}</small><div><button className="mini" onClick={()=>editSite(x)}>EDITAR</button><button className="mini danger" onClick={()=>deleteSite(x)}>EXCLUIR</button></div></div>)}{c.contacts.map(x=><div className="base-item" key={x.id}><small>• WhatsApp {x.phone}{x.name?" — "+x.name:""}</small><div><button className="mini" onClick={()=>editContact(x)}>EDITAR</button><button className="mini danger" onClick={()=>deleteContact(x)}>EXCLUIR</button></div></div>)}</article>)}</div></section>
 </div>
}
